/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.bank;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jehadur
 */
public class MailPanel extends javax.swing.JPanel {

    /**
     * Creates new form MailPanel
     */
    public MailPanel() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mailPanel = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mailPanel.setBackground(new java.awt.Color(0, 204, 204));
        mailPanel.setPreferredSize(new java.awt.Dimension(810, 100));
        mailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setFont(new java.awt.Font("Serif", 0, 21)); // NOI18N
        text.setText("Text :");
        mailPanel.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        from.setFont(new java.awt.Font("Serif", 0, 21)); // NOI18N
        from.setText("From:");
        mailPanel.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        subject.setFont(new java.awt.Font("Serif", 0, 21)); // NOI18N
        subject.setText("Subject :");
        mailPanel.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        add(mailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getFrom() {
        return from;
    }

    public void setFrom(JLabel from) {
        this.from = from;
    }

    public JPanel getMailPanel() {
        return mailPanel;
    }

    public void setMailPanel(JPanel mailPanel) {
        this.mailPanel = mailPanel;
    }

    public JLabel getSubject() {
        return subject;
    }

    public void setSubject(JLabel subject) {
        this.subject = subject;
    }

    public JLabel getText() {
        return text;
    }

    public void setText(JLabel text) {
        this.text = text;
    }
    
     void change(String f, String s, String t)
    {
        from.setText(f);
        subject.setText(s);
        text.setText(t);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel from;
    private javax.swing.JPanel mailPanel;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
