/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.bank;

import Animacion.Animacion;
import java.awt.Cursor;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import keeptoo.Drag;
import ca.bank.MailVar;
import com.sun.mail.pop3.POP3Store;
import java.io.IOException;
import java.util.Properties;
import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.NoSuchProviderException;
import javax.mail.Session;
import com.sun.mail.pop3.*;
import function.Method;
import javax.mail.Store;
import main.Main;

/**
 *
 * @author Chondromollika_Ahmed
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    public Manager() {
        
        this.setUndecorated(true);
        
        initComponents();
        this.setLocationRelativeTo(this);
        separ.setVisible(false);
        
         fadeFrame.JFrameFadeIn(0.0f, 1.0f, 0.005f, 10, this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mailPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        edit2 = new keeptoo.KButton();
        menu_panel = new keeptoo.KGradientPanel();
        btn_feedback = new javax.swing.JButton();
        btn_chat = new javax.swing.JButton();
        lbl_feedb = new javax.swing.JLabel();
        lbl_chat = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        feedb = new javax.swing.JLabel();
        chat = new javax.swing.JLabel();
        separ = new javax.swing.JSeparator();
        info6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JButton();
        flower = new javax.swing.JLabel();
        line_chat = new javax.swing.JLabel();
        line_feedb = new javax.swing.JLabel();
        lbl_feedb_bg = new javax.swing.JLabel();
        lbl_chat_bg = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        combined_panel = new javax.swing.JPanel();
        pnl_addm = new javax.swing.JPanel();
        pnl_chat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnl_feedb = new javax.swing.JPanel();
        read_mail_scroll = new javax.swing.JScrollPane();
        pnl_transfr = new javax.swing.JPanel();
        pnl_dash = new javax.swing.JPanel();
        layer_pane_pp = new javax.swing.JLayeredPane();
        border = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        pan_dash_profile_bg = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_dash_accNo = new javax.swing.JLabel();
        lbl_dash_userName = new javax.swing.JLabel();
        lbl_dash_email = new javax.swing.JLabel();
        lbl_dash_firstName = new javax.swing.JLabel();
        lbl_dash_lastName = new javax.swing.JLabel();
        lbl_dash_st = new javax.swing.JLabel();
        lbl_dash_st1 = new javax.swing.JLabel();
        pnl_dash_dashboard = new javax.swing.JPanel();
        kGradientPanel11 = new ca.bank.KGradientPanel();
        lbl_dash_blance3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kGradientPanel9 = new ca.bank.KGradientPanel();
        lbl_dash_blance4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kGradientPanel10 = new ca.bank.KGradientPanel();
        lbl_dash_blance5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel7 = new ca.bank.KGradientPanel();
        lbl_dash_blance2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel8 = new ca.bank.KGradientPanel();
        lbl_dash_accType = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kGradientPanel4 = new ca.bank.KGradientPanel();
        lbl_dash_blance = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnl_dash_showInfoButton = new ca.bank.KGradientPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        kGradientPanel18 = new ca.bank.KGradientPanel();
        lbl_dash_edit_accNo = new javax.swing.JLabel();
        pnl_dash_userinfo_edit = new javax.swing.JPanel();
        lbl_dashv_ln1 = new javax.swing.JLabel();
        lbl_dashv_dob1 = new javax.swing.JLabel();
        lbl_dashv_gender1 = new javax.swing.JLabel();
        lbl_dashv_mobile1 = new javax.swing.JLabel();
        lbl_dashv_address1 = new javax.swing.JLabel();
        lbl_dashv_zip1 = new javax.swing.JLabel();
        lbl_dashv_occu1 = new javax.swing.JLabel();
        lbl_dashv_marital1 = new javax.swing.JLabel();
        lbl_dashv_country1 = new javax.swing.JLabel();
        lbl_dashv_fn1 = new javax.swing.JLabel();
        lbl_dashv_nid1 = new javax.swing.JLabel();
        kGradientPanel20 = new ca.bank.KGradientPanel();
        jLabel27 = new javax.swing.JLabel();
        pnl_dash_returnbutton1 = new ca.bank.KGradientPanel();
        jLabel28 = new javax.swing.JLabel();
        pan_layer_nid1 = new javax.swing.JPanel();
        lbl_nid1 = new javax.swing.JLabel();
        pnl_dash_saveInfoButton = new ca.bank.KGradientPanel();
        jLabel29 = new javax.swing.JLabel();
        tf_edit_zip = new javax.swing.JTextField();
        tf_edit_addr = new javax.swing.JTextField();
        tf_edit_num = new javax.swing.JTextField();
        tf_edit_ln = new javax.swing.JTextField();
        tf_edit_nid = new javax.swing.JTextField();
        tf_edit_fn = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        combo_country = new javax.swing.JComboBox<>();
        combo_gender = new javax.swing.JComboBox<>();
        combo_occu = new javax.swing.JComboBox<>();
        dob = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        kGradientPanel17 = new ca.bank.KGradientPanel();
        jLabel17 = new javax.swing.JLabel();
        pnl_dash_userinfo = new javax.swing.JPanel();
        lbl_dashv_ln = new javax.swing.JLabel();
        lbl_dashv_dob = new javax.swing.JLabel();
        lbl_dashv_gender = new javax.swing.JLabel();
        lbl_dashv_mobile = new javax.swing.JLabel();
        lbl_dashv_address = new javax.swing.JLabel();
        lbl_dashv_zip = new javax.swing.JLabel();
        lbl_dashv_occu = new javax.swing.JLabel();
        lbl_dashv_marital = new javax.swing.JLabel();
        lbl_dashv_country = new javax.swing.JLabel();
        lbl_dashv_fn = new javax.swing.JLabel();
        lbl_dashv_nid = new javax.swing.JLabel();
        kGradientPanel19 = new ca.bank.KGradientPanel();
        jLabel24 = new javax.swing.JLabel();
        pnl_dash_returnbutton = new ca.bank.KGradientPanel();
        jLabel23 = new javax.swing.JLabel();
        pan_layer_nid = new javax.swing.JPanel();
        lbl_nid = new javax.swing.JLabel();
        pnl_dash_editInfoButton = new ca.bank.KGradientPanel();
        jLabel25 = new javax.swing.JLabel();
        layer_pane_bg = new javax.swing.JLayeredPane();
        lb_dash_bg = new javax.swing.JLabel();
        pnl_tran = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_tran = new javax.swing.JTable();
        pnl_feedb1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mail = new javax.swing.JTextArea();
        bg_panel = new javax.swing.JPanel();
        header = new keeptoo.KGradientPanel();
        exit = new javax.swing.JButton();
        min = new javax.swing.JButton();
        max = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ca_rotate = new javax.swing.JPanel();
        ca_r_l = new javax.swing.JLabel();
        sign_out = new javax.swing.JButton();

        mailPanel.setBackground(new java.awt.Color(0, 204, 204));
        mailPanel.setPreferredSize(new java.awt.Dimension(810, 100));
        mailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 21)); // NOI18N
        jLabel1.setText("Text :");
        mailPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 0, 21)); // NOI18N
        jLabel12.setText("From:");
        mailPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 0, 21)); // NOI18N
        jLabel13.setText("Subject :");
        mailPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        edit2.setBackground(new java.awt.Color(51, 255, 0));
        edit2.setBorder(null);
        edit2.setForeground(new java.awt.Color(51, 102, 0));
        edit2.setText("Edit Profile");
        edit2.setBorderPainted(false);
        edit2.setFocusable(false);
        edit2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        edit2.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        edit2.setkBorderRadius(35);
        edit2.setkEndColor(new java.awt.Color(255, 204, 255));
        edit2.setkFillButton(false);
        edit2.setkForeGround(new java.awt.Color(51, 51, 51));
        edit2.setkHoverForeGround(new java.awt.Color(0, 255, 255));
        edit2.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        edit2.setkIndicatorThickness(10);
        edit2.setkPressedColor(new java.awt.Color(255, 102, 102));
        edit2.setkSelectedColor(new java.awt.Color(0, 255, 0));
        edit2.setkStartColor(new java.awt.Color(0, 255, 255));
        edit2.setMargin(new java.awt.Insets(4, 4, 4, 4));
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_panel.setkEndColor(new java.awt.Color(204, 204, 204));
        menu_panel.setkStartColor(new java.awt.Color(204, 255, 204));
        menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_feedback.setForeground(new java.awt.Color(255, 255, 255));
        btn_feedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_feedback_64px.png"))); // NOI18N
        btn_feedback.setBorder(null);
        btn_feedback.setBorderPainted(false);
        btn_feedback.setContentAreaFilled(false);
        btn_feedback.setFocusPainted(false);
        btn_feedback.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_feedback_64px_1.png"))); // NOI18N
        btn_feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_feedbackMouseClicked(evt);
            }
        });
        btn_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feedbackActionPerformed(evt);
            }
        });
        menu_panel.add(btn_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 60, 60));

        btn_chat.setForeground(new java.awt.Color(255, 255, 255));
        btn_chat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_chat_64px.png"))); // NOI18N
        btn_chat.setBorder(null);
        btn_chat.setBorderPainted(false);
        btn_chat.setContentAreaFilled(false);
        btn_chat.setFocusPainted(false);
        btn_chat.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_chat_64px_1.png"))); // NOI18N
        btn_chat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_chatMouseClicked(evt);
            }
        });
        btn_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chatActionPerformed(evt);
            }
        });
        menu_panel.add(btn_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 60, 60));

        lbl_feedb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_feedbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_feedbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_feedbMouseExited(evt);
            }
        });
        menu_panel.add(lbl_feedb, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 423, 244, 60));

        lbl_chat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_chatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_chatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_chatMouseExited(evt);
            }
        });
        menu_panel.add(lbl_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 493, 244, 60));

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/logos/ca_bank_small.png"))); // NOI18N
        menu_panel.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 572, -1, -1));

        feedb.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        feedb.setForeground(new java.awt.Color(51, 0, 51));
        feedb.setText("READ FeedBack");
        menu_panel.add(feedb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        chat.setFont(new java.awt.Font("Segoe Script", 0, 28)); // NOI18N
        chat.setForeground(new java.awt.Color(51, 0, 51));
        chat.setText("Chat");
        menu_panel.add(chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        separ.setForeground(new java.awt.Color(0, 153, 255));
        separ.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        separ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        separ.setOpaque(true);
        menu_panel.add(separ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 220, 10));

        info6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_about_me_female_64px.png"))); // NOI18N
        info6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info6MouseClicked(evt);
            }
        });
        menu_panel.add(info6, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 575, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menu_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 640));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_sidebar_menu_45px_1.png"))); // NOI18N
        menu.setBorder(null);
        menu.setContentAreaFilled(false);
        menu.setFocusPainted(false);
        menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_sidebar_menu_45px.png"))); // NOI18N
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        menu_panel.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 40, 40));

        flower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_bank_127px.png"))); // NOI18N
        menu_panel.add(flower, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        line_chat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_horizontal_line_127px_1.png"))); // NOI18N
        menu_panel.add(line_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 532, 120, 20));

        line_feedb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_horizontal_line_127px_1.png"))); // NOI18N
        menu_panel.add(line_feedb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 462, 120, 20));

        lbl_feedb_bg.setBackground(new java.awt.Color(204, 255, 255));
        lbl_feedb_bg.setOpaque(true);
        lbl_feedb_bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_feedb_bgMouseClicked(evt);
            }
        });
        menu_panel.add(lbl_feedb_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 423, 244, 60));

        lbl_chat_bg.setBackground(new java.awt.Color(204, 255, 255));
        lbl_chat_bg.setOpaque(true);
        lbl_chat_bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_chat_bgMouseClicked(evt);
            }
        });
        menu_panel.add(lbl_chat_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 493, 244, 60));

        jLabel14.setFont(new java.awt.Font("SimSun", 0, 21)); // NOI18N
        jLabel14.setText("start Server");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        menu_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        getContentPane().add(menu_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 640));

        combined_panel.setLayout(new java.awt.CardLayout());

        pnl_addm.setBackground(new java.awt.Color(255, 255, 255));
        pnl_addm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnl_addmLayout = new javax.swing.GroupLayout(pnl_addm);
        pnl_addm.setLayout(pnl_addmLayout);
        pnl_addmLayout.setHorizontalGroup(
            pnl_addmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        pnl_addmLayout.setVerticalGroup(
            pnl_addmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        combined_panel.add(pnl_addm, "card2");

        pnl_chat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel3.setText("chat");

        javax.swing.GroupLayout pnl_chatLayout = new javax.swing.GroupLayout(pnl_chat);
        pnl_chat.setLayout(pnl_chatLayout);
        pnl_chatLayout.setHorizontalGroup(
            pnl_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_chatLayout.createSequentialGroup()
                .addGap(491, 491, 491)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_chatLayout.setVerticalGroup(
            pnl_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_chatLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        combined_panel.add(pnl_chat, "card3");

        pnl_feedb.setPreferredSize(new java.awt.Dimension(810, 570));
        pnl_feedb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnl_feedb.add(read_mail_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        combined_panel.add(pnl_feedb, "card4");

        pnl_transfr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout pnl_transfrLayout = new javax.swing.GroupLayout(pnl_transfr);
        pnl_transfr.setLayout(pnl_transfrLayout);
        pnl_transfrLayout.setHorizontalGroup(
            pnl_transfrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_transfrLayout.setVerticalGroup(
            pnl_transfrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        combined_panel.add(pnl_transfr, "card5");

        pnl_dash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layer_pane_pp.setLayout(new javax.swing.OverlayLayout(layer_pane_pp));

        border.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/images/border.png"))); // NOI18N
        border.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        border.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        border.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borderMouseClicked(evt);
            }
        });
        layer_pane_pp.add(border);

        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/images/profile.png"))); // NOI18N
        layer_pane_pp.add(profile);

        pnl_dash.add(layer_pane_pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        pan_dash_profile_bg.setBackground(new java.awt.Color(255, 255, 255));
        pan_dash_profile_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Username:");
        pan_dash_profile_bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 22, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Acc No:");
        pan_dash_profile_bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 60, -1, -1));

        lbl_dash_accNo.setFont(new java.awt.Font("Perpetua", 0, 28)); // NOI18N
        lbl_dash_accNo.setForeground(new java.awt.Color(153, 153, 153));
        lbl_dash_accNo.setText("ABCDEFGH");
        pan_dash_profile_bg.add(lbl_dash_accNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 65, -1, -1));

        lbl_dash_userName.setFont(new java.awt.Font("Perpetua", 0, 28)); // NOI18N
        lbl_dash_userName.setForeground(new java.awt.Color(204, 204, 204));
        lbl_dash_userName.setText("Chondromollika");
        pan_dash_profile_bg.add(lbl_dash_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 25, -1, -1));

        lbl_dash_email.setFont(new java.awt.Font("Papyrus", 0, 21)); // NOI18N
        lbl_dash_email.setForeground(new java.awt.Color(0, 102, 0));
        lbl_dash_email.setText("chondromollika.ahmed@gmail.com");
        pan_dash_profile_bg.add(lbl_dash_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        lbl_dash_firstName.setFont(new java.awt.Font("Castellar", 0, 28)); // NOI18N
        lbl_dash_firstName.setForeground(new java.awt.Color(0, 204, 255));
        lbl_dash_firstName.setText("Chondromollika ");
        pan_dash_profile_bg.add(lbl_dash_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        lbl_dash_lastName.setFont(new java.awt.Font("Castellar", 0, 28)); // NOI18N
        lbl_dash_lastName.setForeground(new java.awt.Color(0, 153, 153));
        lbl_dash_lastName.setText("Ahmed");
        pan_dash_profile_bg.add(lbl_dash_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        lbl_dash_st.setFont(new java.awt.Font("Papyrus", 0, 21)); // NOI18N
        lbl_dash_st.setForeground(new java.awt.Color(0, 102, 0));
        lbl_dash_st.setText("Status:");
        pan_dash_profile_bg.add(lbl_dash_st, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        lbl_dash_st1.setFont(new java.awt.Font("Papyrus", 0, 21)); // NOI18N
        lbl_dash_st1.setForeground(new java.awt.Color(51, 204, 0));
        lbl_dash_st1.setText("Verified");
        pan_dash_profile_bg.add(lbl_dash_st1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        pnl_dash.add(pan_dash_profile_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 120));

        pnl_dash_dashboard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnl_dash_dashboard.setOpaque(false);
        pnl_dash_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel11.setkBorderRadius(20);
        kGradientPanel11.setkEndColor(new java.awt.Color(204, 255, 255));
        kGradientPanel11.setkStartColor(new java.awt.Color(255, 102, 255));
        kGradientPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dash_blance3.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        lbl_dash_blance3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dash_blance3.setText("0.00/-");
        kGradientPanel11.add(lbl_dash_blance3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jLabel9.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel9.setText("Blance");
        kGradientPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, -1, -1));

        pnl_dash_dashboard.add(kGradientPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 100));

        kGradientPanel9.setkBorderRadius(20);
        kGradientPanel9.setkEndColor(new java.awt.Color(51, 255, 51));
        kGradientPanel9.setkGradientFocus(450);
        kGradientPanel9.setkStartColor(new java.awt.Color(255, 102, 153));
        kGradientPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dash_blance4.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        lbl_dash_blance4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dash_blance4.setText("0.00/-");
        kGradientPanel9.add(lbl_dash_blance4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jLabel10.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel10.setText("Blance");
        kGradientPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, -1, -1));

        pnl_dash_dashboard.add(kGradientPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 250, 100));

        kGradientPanel10.setkBorderRadius(20);
        kGradientPanel10.setkEndColor(new java.awt.Color(255, 153, 102));
        kGradientPanel10.setkStartColor(new java.awt.Color(255, 0, 102));
        kGradientPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dash_blance5.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        lbl_dash_blance5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dash_blance5.setText("0.00/-");
        kGradientPanel10.add(lbl_dash_blance5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel11.setText("Blance");
        kGradientPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, -1, -1));

        pnl_dash_dashboard.add(kGradientPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, 100));

        kGradientPanel7.setkBorderRadius(20);
        kGradientPanel7.setkEndColor(new java.awt.Color(51, 255, 255));
        kGradientPanel7.setkStartColor(new java.awt.Color(255, 153, 153));
        kGradientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dash_blance2.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        lbl_dash_blance2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dash_blance2.setText("0.00/-");
        kGradientPanel7.add(lbl_dash_blance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jLabel8.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel8.setText("Blance");
        kGradientPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, -1, -1));

        pnl_dash_dashboard.add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, 100));

        kGradientPanel8.setkBorderRadius(20);
        kGradientPanel8.setkEndColor(new java.awt.Color(255, 153, 153));
        kGradientPanel8.setkStartColor(new java.awt.Color(102, 255, 204));
        kGradientPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dash_accType.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        lbl_dash_accType.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dash_accType.setText("Saving");
        kGradientPanel8.add(lbl_dash_accType, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 50, 140, -1));

        jLabel7.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_bank_40px.png"))); // NOI18N
        jLabel7.setText("Account Type");
        kGradientPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, -1, -1));

        pnl_dash_dashboard.add(kGradientPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 250, 100));

        kGradientPanel4.setkBorderRadius(20);
        kGradientPanel4.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(102, 204, 255));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dash_blance.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        lbl_dash_blance.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dash_blance.setText("0.00/-");
        kGradientPanel4.add(lbl_dash_blance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel4.setText("Blance");
        kGradientPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, -1, -1));

        pnl_dash_dashboard.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, 100));

        pnl_dash_showInfoButton.setkBorderRadius(20);
        pnl_dash_showInfoButton.setkEndColor(new java.awt.Color(255, 153, 102));
        pnl_dash_showInfoButton.setkStartColor(new java.awt.Color(255, 0, 102));
        pnl_dash_showInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_dash_showInfoButtonMouseClicked(evt);
            }
        });
        pnl_dash_showInfoButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel26.setText("View Information");
        pnl_dash_showInfoButton.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        pnl_dash_dashboard.add(pnl_dash_showInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 150, 50));

        pnl_dash.add(pnl_dash_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel18.setkBorderRadius(20);
        kGradientPanel18.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel18.setkStartColor(new java.awt.Color(102, 204, 255));
        kGradientPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dash_edit_accNo.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        lbl_dash_edit_accNo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dash_edit_accNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        lbl_dash_edit_accNo.setText("Ac-");
        kGradientPanel18.add(lbl_dash_edit_accNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jPanel8.add(kGradientPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, 50));

        pnl_dash_userinfo_edit.setOpaque(false);
        pnl_dash_userinfo_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dashv_ln1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_ln1.setText("Last Name:");
        pnl_dash_userinfo_edit.add(lbl_dashv_ln1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, -1, -1));

        lbl_dashv_dob1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_dob1.setText("Date Of Birth:");
        pnl_dash_userinfo_edit.add(lbl_dashv_dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, -1, -1));

        lbl_dashv_gender1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_gender1.setText("Gender:");
        pnl_dash_userinfo_edit.add(lbl_dashv_gender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, -1, -1));

        lbl_dashv_mobile1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_mobile1.setText("Mobile:");
        pnl_dash_userinfo_edit.add(lbl_dashv_mobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, -1, -1));

        lbl_dashv_address1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_address1.setText("Adress:");
        pnl_dash_userinfo_edit.add(lbl_dashv_address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 270, -1, -1));

        lbl_dashv_zip1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_zip1.setText("Zip Code:");
        pnl_dash_userinfo_edit.add(lbl_dashv_zip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 310, -1, -1));

        lbl_dashv_occu1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_occu1.setText("Occupation:");
        pnl_dash_userinfo_edit.add(lbl_dashv_occu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        lbl_dashv_marital1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_marital1.setText("Marital Status:");
        pnl_dash_userinfo_edit.add(lbl_dashv_marital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        lbl_dashv_country1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_country1.setText("Country:");
        pnl_dash_userinfo_edit.add(lbl_dashv_country1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        lbl_dashv_fn1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_fn1.setText("First Name:");
        pnl_dash_userinfo_edit.add(lbl_dashv_fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, -1, -1));

        lbl_dashv_nid1.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_nid1.setText("NID :");
        pnl_dash_userinfo_edit.add(lbl_dashv_nid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        kGradientPanel20.setToolTipText("return to dashboard");
        kGradientPanel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel20.setkBorderRadius(20);
        kGradientPanel20.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel20.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel27.setText("ADD");
        kGradientPanel20.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        pnl_dash_userinfo_edit.add(kGradientPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 100, 50));

        pnl_dash_returnbutton1.setToolTipText("return to dashboard");
        pnl_dash_returnbutton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnl_dash_returnbutton1.setkBorderRadius(20);
        pnl_dash_returnbutton1.setkEndColor(new java.awt.Color(153, 204, 255));
        pnl_dash_returnbutton1.setkStartColor(new java.awt.Color(51, 51, 51));
        pnl_dash_returnbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_dash_returnbutton1MouseClicked(evt);
            }
        });
        pnl_dash_returnbutton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel28.setText("Cancel Edit");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        pnl_dash_returnbutton1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        pnl_dash_userinfo_edit.add(pnl_dash_returnbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, 50));

        pan_layer_nid1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pan_layer_nid1.setOpaque(false);
        pan_layer_nid1.setLayout(new javax.swing.OverlayLayout(pan_layer_nid1));

        lbl_nid1.setBorder(new javax.swing.border.MatteBorder(null));
        lbl_nid1.setPreferredSize(new java.awt.Dimension(130, 130));
        pan_layer_nid1.add(lbl_nid1);

        pnl_dash_userinfo_edit.add(pan_layer_nid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 130, 130));

        pnl_dash_saveInfoButton.setToolTipText("return to dashboard");
        pnl_dash_saveInfoButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnl_dash_saveInfoButton.setkBorderRadius(20);
        pnl_dash_saveInfoButton.setkEndColor(new java.awt.Color(153, 204, 255));
        pnl_dash_saveInfoButton.setkStartColor(new java.awt.Color(102, 204, 0));
        pnl_dash_saveInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_dash_saveInfoButtonMouseClicked(evt);
            }
        });
        pnl_dash_saveInfoButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel29.setText("Save");
        pnl_dash_saveInfoButton.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        pnl_dash_userinfo_edit.add(pnl_dash_saveInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 100, 50));

        tf_edit_zip.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        tf_edit_zip.setText("Zip Code");
        pnl_dash_userinfo_edit.add(tf_edit_zip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 170, -1));

        tf_edit_addr.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        tf_edit_addr.setText("Address");
        tf_edit_addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_edit_addrActionPerformed(evt);
            }
        });
        pnl_dash_userinfo_edit.add(tf_edit_addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 170, -1));

        tf_edit_num.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        tf_edit_num.setText("01993522240");
        pnl_dash_userinfo_edit.add(tf_edit_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 170, -1));

        tf_edit_ln.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        tf_edit_ln.setText("Last Name");
        pnl_dash_userinfo_edit.add(tf_edit_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, -1));

        tf_edit_nid.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        tf_edit_nid.setText("ID Number");
        tf_edit_nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_edit_nidActionPerformed(evt);
            }
        });
        pnl_dash_userinfo_edit.add(tf_edit_nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 250, -1));

        tf_edit_fn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        tf_edit_fn.setText("First Name");
        tf_edit_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_edit_fnActionPerformed(evt);
            }
        });
        pnl_dash_userinfo_edit.add(tf_edit_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, -1));

        jCheckBox1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jCheckBox1.setText("Unmarried");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        pnl_dash_userinfo_edit.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 130, 30));

        jCheckBox2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jCheckBox2.setText("Married");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        pnl_dash_userinfo_edit.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 110, 30));

        combo_country.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        combo_country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangladesh" }));
        combo_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_countryActionPerformed(evt);
            }
        });
        pnl_dash_userinfo_edit.add(combo_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        combo_gender.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        pnl_dash_userinfo_edit.add(combo_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        combo_occu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        combo_occu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Public Servant", "Business", "Student" }));
        pnl_dash_userinfo_edit.add(combo_occu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));
        pnl_dash_userinfo_edit.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jPanel8.add(pnl_dash_userinfo_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 810, 430));

        pnl_dash.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel17.setkBorderRadius(20);
        kGradientPanel17.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel17.setkStartColor(new java.awt.Color(102, 204, 255));
        kGradientPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel17.setText("Blance");
        kGradientPanel17.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jPanel7.add(kGradientPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, 50));

        pnl_dash_userinfo.setOpaque(false);
        pnl_dash_userinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dashv_ln.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_ln.setText("Last Name:");
        pnl_dash_userinfo.add(lbl_dashv_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, -1, -1));

        lbl_dashv_dob.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_dob.setText("Date Of Birth:");
        pnl_dash_userinfo.add(lbl_dashv_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, -1, -1));

        lbl_dashv_gender.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_gender.setText("Gender:");
        pnl_dash_userinfo.add(lbl_dashv_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, -1, -1));

        lbl_dashv_mobile.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_mobile.setText("Mobile:");
        pnl_dash_userinfo.add(lbl_dashv_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, -1, -1));

        lbl_dashv_address.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_address.setText("Adress:");
        pnl_dash_userinfo.add(lbl_dashv_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 270, -1, -1));

        lbl_dashv_zip.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_zip.setText("Zip Code:");
        pnl_dash_userinfo.add(lbl_dashv_zip, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 310, -1, -1));

        lbl_dashv_occu.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_occu.setText("Occupation:");
        pnl_dash_userinfo.add(lbl_dashv_occu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        lbl_dashv_marital.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_marital.setText("Marital Status:");
        pnl_dash_userinfo.add(lbl_dashv_marital, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        lbl_dashv_country.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_country.setText("Country:");
        pnl_dash_userinfo.add(lbl_dashv_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        lbl_dashv_fn.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_fn.setText("First Name:");
        pnl_dash_userinfo.add(lbl_dashv_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, -1, -1));

        lbl_dashv_nid.setFont(new java.awt.Font("Sylfaen", 0, 21)); // NOI18N
        lbl_dashv_nid.setText("NID :");
        pnl_dash_userinfo.add(lbl_dashv_nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        kGradientPanel19.setToolTipText("return to dashboard");
        kGradientPanel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kGradientPanel19.setkBorderRadius(20);
        kGradientPanel19.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel19.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel24.setText("ADD");
        kGradientPanel19.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        pnl_dash_userinfo.add(kGradientPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 100, 50));

        pnl_dash_returnbutton.setToolTipText("return to dashboard");
        pnl_dash_returnbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnl_dash_returnbutton.setkBorderRadius(20);
        pnl_dash_returnbutton.setkEndColor(new java.awt.Color(153, 204, 255));
        pnl_dash_returnbutton.setkStartColor(new java.awt.Color(51, 51, 51));
        pnl_dash_returnbutton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel23.setText("Return To Dashboard");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        pnl_dash_returnbutton.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        pnl_dash_userinfo.add(pnl_dash_returnbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, 50));

        pan_layer_nid.setBorder(new javax.swing.border.MatteBorder(null));
        pan_layer_nid.setOpaque(false);
        pan_layer_nid.setLayout(new javax.swing.OverlayLayout(pan_layer_nid));
        pan_layer_nid.add(lbl_nid);

        pnl_dash_userinfo.add(pan_layer_nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 130, 130));

        pnl_dash_editInfoButton.setToolTipText("return to dashboard");
        pnl_dash_editInfoButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnl_dash_editInfoButton.setkBorderRadius(20);
        pnl_dash_editInfoButton.setkEndColor(new java.awt.Color(153, 204, 255));
        pnl_dash_editInfoButton.setkStartColor(new java.awt.Color(102, 204, 0));
        pnl_dash_editInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_dash_editInfoButtonMouseClicked(evt);
            }
        });
        pnl_dash_editInfoButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_dollar_euro_exchange_40px.png"))); // NOI18N
        jLabel25.setText("EDIT");
        pnl_dash_editInfoButton.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        pnl_dash_userinfo.add(pnl_dash_editInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 100, 50));

        jPanel7.add(pnl_dash_userinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 810, 430));

        pnl_dash.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        layer_pane_bg.setLayout(new javax.swing.OverlayLayout(layer_pane_bg));

        lb_dash_bg.setPreferredSize(new java.awt.Dimension(100, 100));
        layer_pane_bg.add(lb_dash_bg);

        pnl_dash.add(layer_pane_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        combined_panel.add(pnl_dash, "card7");

        pnl_tran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_tran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tran ID", "Ref.", "Debit", "Credit", "Date", "User", "ACC.", "Reciepent", "Status", "ConcUr"
            }
        ));
        jScrollPane1.setViewportView(table_tran);

        pnl_tran.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 810, 440));

        combined_panel.add(pnl_tran, "card6");

        pnl_feedb1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ta_mail.setColumns(20);
        ta_mail.setRows(5);
        jScrollPane2.setViewportView(ta_mail);

        pnl_feedb1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 770, 530));

        combined_panel.add(pnl_feedb1, "card4");

        getContentPane().add(combined_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 810, 570));

        bg_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setkEndColor(new java.awt.Color(255, 153, 204));
        header.setkStartColor(new java.awt.Color(204, 255, 204));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_exit_32px.png"))); // NOI18N
        exit.setBorder(null);
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setFocusPainted(false);
        exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_exit_32px_1.png"))); // NOI18N
        exit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_exit_64px.png"))); // NOI18N
        exit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_exit_40px_1.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 0, 30, -1));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_minimize_window_32px_1.png"))); // NOI18N
        min.setBorder(null);
        min.setBorderPainted(false);
        min.setContentAreaFilled(false);
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.setFocusPainted(false);
        min.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_minimize_window_32px.png"))); // NOI18N
        min.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_exit_64px.png"))); // NOI18N
        min.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_exit_40px_1.png"))); // NOI18N
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        header.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 0, 30, -1));

        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_full_screen_32px.png"))); // NOI18N
        max.setBorder(null);
        max.setBorderPainted(false);
        max.setContentAreaFilled(false);
        max.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        max.setFocusPainted(false);
        max.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_full_screen_32px_1.png"))); // NOI18N
        max.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_exit_64px.png"))); // NOI18N
        max.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_exit_40px_1.png"))); // NOI18N
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxActionPerformed(evt);
            }
        });
        header.add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 0, 30, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manager  Interface");
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 300, -1));

        bg_panel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        ca_r_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/logos/ca_rotate.png"))); // NOI18N
        ca_r_l.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout ca_rotateLayout = new javax.swing.GroupLayout(ca_rotate);
        ca_rotate.setLayout(ca_rotateLayout);
        ca_rotateLayout.setHorizontalGroup(
            ca_rotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ca_rotateLayout.createSequentialGroup()
                .addComponent(ca_r_l, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        ca_rotateLayout.setVerticalGroup(
            ca_rotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ca_rotateLayout.createSequentialGroup()
                .addComponent(ca_r_l)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg_panel.add(ca_rotate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 200, 610));

        sign_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_shutdown_40px.png"))); // NOI18N
        sign_out.setBorder(null);
        sign_out.setContentAreaFilled(false);
        sign_out.setFocusPainted(false);
        sign_out.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_sidebar_menu_45px.png"))); // NOI18N
        sign_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_outActionPerformed(evt);
            }
        });
        bg_panel.add(sign_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 30, 40, 40));

        getContentPane().add(bg_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int dialog=JOptionPane.YES_NO_CANCEL_OPTION;
        
        int result=JOptionPane.showConfirmDialog(null, "Leave CA Bank", "ca bank", dialog);
        
         if(result==0)
         {
             System.exit(0);
         }
    }//GEN-LAST:event_exitActionPerformed

    
    int loc_x,loc_y;
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-loc_x, y-loc_y);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        header.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        loc_x=evt.getX();
        loc_y=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minActionPerformed

    boolean maximize=true;
    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
        // TODO add your handling code here:
        if(maximize)
        {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env=GraphicsEnvironment.getLocalGraphicsEnvironment();
            this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximize=false;
        }
        else
        {
            this.setExtendedState(JFrame.NORMAL);
            maximize=true;
        }
        
    }//GEN-LAST:event_maxActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        
        if(menu_panel.getX()==-200)
        {
           
           Animacion.mover_derecha(-200,0,10,10,menu_panel); 
           separ.setVisible(true);
//           this.menu_panel.setLocation(100, 0);
//           this.menu_panel.revalidate();
//           this.menu_panel.repaint();
//           System.out.println(" "+menu_panel.getX());
//          
        }
        else
        {   
            
            Animacion.mover_izquierda(0, -200, 10, 10, menu_panel);
            separ.setVisible(false);
            
            
//            this.menu_panel.setLocation(-200, 0);
//            System.out.println(" "+menu_panel.getX());
//           this.menu_panel.revalidate();
//           this.menu_panel.repaint();
//            
           
        }
        
     //   Animacion.mover_izquierda(0,-200,10,10,menu_panel);
        
    }//GEN-LAST:event_menuActionPerformed

    private void btn_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feedbackActionPerformed
        new CombinedPanel(combined_panel,pnl_feedb);
    }//GEN-LAST:event_btn_feedbackActionPerformed

    private void sign_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_outActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_outActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
        
        Image img = Toolkit.getDefaultToolkit().getImage("src\\ca\\bank\\resources\\logos\\ca-only.png");  
          this.setIconImage(img);
          this.setTitle("CA BANK ["+ClientVar.getUsername()+"]");

        // TODO add your handling code here:
        lbl_dash_userName.setText(ClientVar.getUsername());
        lbl_dash_firstName.setText(ClientVar.getFirstName());
        lbl_dash_lastName.setText(ClientVar.getLastName());
        lbl_dash_email.setText(ClientVar.getEmail());
        
        
        lbl_dashv_fn.setText("First Name: "+ClientVar.getFirstName());
        lbl_dashv_ln.setText("Last Name: "+ClientVar.getLastName());
        //lbl_dash_firstName.setText(ClientVar.getFirstName());
        
        
        pnl_dash_userinfo.setVisible(false);
        pnl_dash_userinfo_edit.setVisible(false);
        
        pnl_dash_dashboard.setVisible(true);
        read_mail_scroll.add(new MailPanel());
        new CombinedPanel(combined_panel,pnl_feedb);
        
       
      
        line_feedb.setVisible(false);
        line_chat.setVisible(false);
        
        
       
        
        
        
        lbl_feedb_bg.setVisible(false);
        lbl_chat_bg.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void lbl_feedbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_feedbMouseClicked

//        line_dash.setVisible(false);
//        line_tran.setVisible(false);
//        line_addm.setVisible(false);
//        line_transfr.setVisible(false);
//        line_feedb.setVisible(true);
//        line_chat.setVisible(false);
//        



      new CombinedPanel(combined_panel,pnl_feedb1);
        new ReceiveMail().main(null);
                
        Message[] m=MailVar.getMsg();
        
        
        for (int i = 0; i < m.length; i++) {
            try {
                Message message = m[i];
                 String str=message.getFrom()[0].toString();
                 if(str.indexOf("CA")!=-1)
        {
                ta_mail.setText(ta_mail.getText()+"Subject: " + message.getSubject());
                ta_mail.setText(ta_mail.getText()+"\n"+"From:" + message.getFrom()[0].toString());
                ta_mail.setText(ta_mail.getText()+"\n"+message.getContent().toString());
                ta_mail.setText(ta_mail.getText()+"\n\n\n"+"~~~~~~~~~~~~~~~~~~~~~~~~~~~~"+"\n");
        }
                
                
//        String str;
//            try {
//                         str = message.getFrom()[0].toString();
//        
//                        if(str.indexOf("CA")!=-1)
//                        {
//                            MailPanel p=new MailPanel();
//                            p.change(message.getFrom()[0].toString(), message.getSubject(), message.getContent().toString());
//                            p.revalidate();
//                            p.repaint();
//                          read_mail_scroll.add(p);
//                          read_mail_scroll.revalidate();
//                          
//                          read_mail_scroll.repaint();
//
//                       
//                        }
//                        else
//                        {
//                            System.out.println("bal");
//                        }
//                 }
//            catch (MessagingException ex) {
//                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (IOException ex) {
//                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            
//        }
            } catch (MessagingException ex) {
                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
       
        
        lbl_feedb_bg.setVisible(true);
        lbl_chat_bg.setVisible(false);
        
    }//GEN-LAST:event_lbl_feedbMouseClicked

    
    
    
    
    boolean call=false;
    
    
    private void lbl_chatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_chatMouseClicked
//        line_dash.setVisible(false);
//        line_tran.setVisible(false);
//        line_addm.setVisible(false);
//        line_transfr.setVisible(false);
//        line_feedb.setVisible(false);
//        line_chat.setVisible(true);
//        
        
        //new CombinedPanel(combined_panel,pnl_chat);
        
        if(!call)
        {
            try
            {
            chatOpen();
            }catch(Exception e)
            {
             JOptionPane.showMessageDialog(this, "Start Server First");
            }
                    
            call=true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Multiple Tab Not Supported Yet");
           // new CombinedPanel(combined_panel, pnl_developer);
        }
        
      
       
      
        
        lbl_feedb_bg.setVisible(false);
        lbl_chat_bg.setVisible(true);
    }//GEN-LAST:event_lbl_chatMouseClicked

    private void lbl_feedb_bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_feedb_bgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_feedb_bgMouseClicked

    private void lbl_chat_bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_chat_bgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_chat_bgMouseClicked

    private void lbl_feedbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_feedbMouseEntered
         line_feedb.setVisible(true);
    }//GEN-LAST:event_lbl_feedbMouseEntered

    private void lbl_feedbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_feedbMouseExited
         line_feedb.setVisible(false);
    }//GEN-LAST:event_lbl_feedbMouseExited

    private void lbl_chatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_chatMouseEntered
         line_chat.setVisible(true);
    }//GEN-LAST:event_lbl_chatMouseEntered

    private void lbl_chatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_chatMouseExited
         line_chat.setVisible(false);
    }//GEN-LAST:event_lbl_chatMouseExited

    private void btn_feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_feedbackMouseClicked
       
        lbl_feedb_bg.setVisible(true);
        lbl_chat_bg.setVisible(false);
    }//GEN-LAST:event_btn_feedbackMouseClicked

    private void btn_chatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chatMouseClicked
        
        lbl_feedb_bg.setVisible(false);
        lbl_chat_bg.setVisible(true);
    }//GEN-LAST:event_btn_chatMouseClicked

    private void btn_chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chatActionPerformed
        new CombinedPanel(combined_panel,pnl_chat);
    }//GEN-LAST:event_btn_chatActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit2ActionPerformed
private ImageIcon profile_pic;
    private void borderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borderMouseClicked
        if (evt.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(evt)) {
            JFileChooser ch = new JFileChooser();
            FileChoose preview = new FileChoose();
            ch.setAccessory(preview);
            ch.addPropertyChangeListener(preview);
            ch.setFileFilter(new FileFilter() {
                @Override
                public boolean accept(File file) {
                    String name = file.getName();
                    return file.isDirectory() || name.endsWith(".png") || name.endsWith(".PNG") || name.endsWith("jpg") || name.endsWith("JPG");
                }

                @Override
                public String getDescription() {
                    return "png,jpg";
                }
            });
            
            int opt = ch.showOpenDialog(this);
            if (opt == JFileChooser.APPROVE_OPTION) {
                ImageIcon image = new ImageIcon(ch.getSelectedFile().getAbsolutePath());
                Image img;
                if (image.getIconWidth() > image.getIconHeight()) {
                    img = image.getImage().getScaledInstance(100, -1, Image.SCALE_SMOOTH);
                } else {
                    img = image.getImage().getScaledInstance(-1, 100, Image.SCALE_SMOOTH);
                }
                profile_pic = new ImageIcon(img);
                profile.setIcon(profile_pic);

            }
        }
    }//GEN-LAST:event_borderMouseClicked
  DatabaseConnect db;
    private void pnl_dash_showInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_dash_showInfoButtonMouseClicked

        pnl_dash_userinfo.setVisible(true);
        pnl_dash_dashboard.setVisible(false);
        
        
        db=new DatabaseConnect();
        String query="select * from acc_info where username=?";
        try {
            db.pst=db.con.prepareStatement(query);
            db.pst.setString(1, ClientVar.getUsername());
            db.rs=db.pst.executeQuery();
            
            if(db.rs.next())
            {
                lbl_dashv_dob.setText("DOB: "+db.rs.getString(2));
                lbl_dashv_gender.setText("Gender: "+db.rs.getString(3));
                lbl_dashv_mobile.setText("Number: "+db.rs.getString(4));
                lbl_dashv_address.setText("Address: "+db.rs.getString(5));
                lbl_dashv_zip.setText("Zip Code: "+db.rs.getString(6));
                lbl_dashv_occu.setText("Occupation: "+db.rs.getString(7));
                lbl_dashv_marital.setText("Marital Status: "+db.rs.getString(8));
                
                lbl_dashv_country.setText("Contry: "+db.rs.getString(9));
                lbl_dashv_nid.setText("NID: "+db.rs.getString(10));
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_pnl_dash_showInfoButtonMouseClicked

    
    
    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked

        pnl_dash_userinfo.setVisible(false);
        pnl_dash_dashboard.setVisible(true);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        pnl_dash_userinfo.setVisible(true);
        pnl_dash_userinfo_edit.setVisible(false);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void tf_edit_addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_edit_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_edit_addrActionPerformed

    private void tf_edit_nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_edit_nidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_edit_nidActionPerformed

    private void tf_edit_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_edit_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_edit_fnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void combo_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_countryActionPerformed

    private void pnl_dash_editInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_dash_editInfoButtonMouseClicked
         pnl_dash_userinfo.setVisible(false);
        pnl_dash_userinfo_edit.setVisible(true);
        
    }//GEN-LAST:event_pnl_dash_editInfoButtonMouseClicked

    private void pnl_dash_returnbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_dash_returnbutton1MouseClicked
        pnl_dash_userinfo.setVisible(true);
        pnl_dash_userinfo_edit.setVisible(false);
        
    }//GEN-LAST:event_pnl_dash_returnbutton1MouseClicked
    String marital="N/A";
    private void pnl_dash_saveInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_dash_saveInfoButtonMouseClicked
        String query= "insert into acc_info (username, acc_no, dob, gender, number, address, zip, occu, marital, country, nid) values(?,?,?,?,?,?,?,?,?,?,?)";

        db=new DatabaseConnect();
        
        SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");
        String date=f.format(dob.getDate());
        
        try {
            db.pst=db.con.prepareStatement(query);
            db.pst.setString(1, "ch1234");
            db.pst.setString(2, "mollika");
            db.pst.setString(3, date);
            db.pst.setString(4, combo_gender.getSelectedItem().toString());
            db.pst.setString(5, tf_edit_num.getText());
            db.pst.setString(6, tf_edit_addr.getText());
            db.pst.setString(7, tf_edit_zip.getText());
            db.pst.setString(8, combo_occu.getSelectedItem().toString());
            db.pst.setString(9, marital);
            db.pst.setString(10, combo_country.getSelectedItem().toString());
            db.pst.setString(11, tf_edit_nid.getText());
            db.pst.executeUpdate();
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_pnl_dash_saveInfoButtonMouseClicked

    
    void chatOpen()
    {
                ImageIcon image = new ImageIcon("src\\ca\\bank\\resources\\images\\image.png");
                Image img;
                if (image.getIconWidth() > image.getIconHeight()) {
                    img = image.getImage().getScaledInstance(50, -1, Image.SCALE_SMOOTH);
                } else {
                    img = image.getImage().getScaledInstance(-1, 50, Image.SCALE_SMOOTH);
                }
                profile_pic = new ImageIcon(img);
                
                
                
                try {
             Method.connect(profile_pic,"CA_Admin","192.168.0.109");//137.1
             Main.setCname("Admin-"+"CA");
             new Main().setVisible(true);
  //             panabcd.start();
           } catch (Exception ex) {
               ex.printStackTrace();
           }
        
        
        
    }
    
    
    
    boolean cl=false;
    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
      
        if(!cl)
       {
           new ca_server.CA_Server().setVisible(true);
       }
        else
        {
            JOptionPane.showMessageDialog(this, "Server Is Already Opened Or UnexpectedError Occured \n If Occured Please Restart The App ");
        }
       cl=true;
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void info6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info6MouseClicked

        //new CombinedPanel(combined_panel, pnl_developer);
    }//GEN-LAST:event_info6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_panel;
    private javax.swing.JLabel border;
    private javax.swing.JButton btn_chat;
    private javax.swing.JButton btn_feedback;
    private javax.swing.JLabel ca_r_l;
    private javax.swing.JPanel ca_rotate;
    private javax.swing.JLabel chat;
    private javax.swing.JPanel combined_panel;
    private javax.swing.JComboBox<String> combo_country;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.JComboBox<String> combo_occu;
    private com.toedter.calendar.JDateChooser dob;
    private keeptoo.KButton edit2;
    private javax.swing.JButton exit;
    private javax.swing.JLabel feedb;
    private javax.swing.JLabel flower;
    private keeptoo.KGradientPanel header;
    private javax.swing.JLabel info;
    private javax.swing.JLabel info6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private ca.bank.KGradientPanel kGradientPanel10;
    private ca.bank.KGradientPanel kGradientPanel11;
    private ca.bank.KGradientPanel kGradientPanel17;
    private ca.bank.KGradientPanel kGradientPanel18;
    private ca.bank.KGradientPanel kGradientPanel19;
    private ca.bank.KGradientPanel kGradientPanel20;
    private ca.bank.KGradientPanel kGradientPanel4;
    private ca.bank.KGradientPanel kGradientPanel7;
    private ca.bank.KGradientPanel kGradientPanel8;
    private ca.bank.KGradientPanel kGradientPanel9;
    private javax.swing.JLayeredPane layer_pane_bg;
    private javax.swing.JLayeredPane layer_pane_pp;
    private javax.swing.JLabel lb_dash_bg;
    private javax.swing.JLabel lbl_chat;
    private javax.swing.JLabel lbl_chat_bg;
    private javax.swing.JLabel lbl_dash_accNo;
    private javax.swing.JLabel lbl_dash_accType;
    private javax.swing.JLabel lbl_dash_blance;
    private javax.swing.JLabel lbl_dash_blance2;
    private javax.swing.JLabel lbl_dash_blance3;
    private javax.swing.JLabel lbl_dash_blance4;
    private javax.swing.JLabel lbl_dash_blance5;
    private javax.swing.JLabel lbl_dash_edit_accNo;
    private javax.swing.JLabel lbl_dash_email;
    private javax.swing.JLabel lbl_dash_firstName;
    private javax.swing.JLabel lbl_dash_lastName;
    private javax.swing.JLabel lbl_dash_st;
    private javax.swing.JLabel lbl_dash_st1;
    private javax.swing.JLabel lbl_dash_userName;
    private javax.swing.JLabel lbl_dashv_address;
    private javax.swing.JLabel lbl_dashv_address1;
    private javax.swing.JLabel lbl_dashv_country;
    private javax.swing.JLabel lbl_dashv_country1;
    private javax.swing.JLabel lbl_dashv_dob;
    private javax.swing.JLabel lbl_dashv_dob1;
    private javax.swing.JLabel lbl_dashv_fn;
    private javax.swing.JLabel lbl_dashv_fn1;
    private javax.swing.JLabel lbl_dashv_gender;
    private javax.swing.JLabel lbl_dashv_gender1;
    private javax.swing.JLabel lbl_dashv_ln;
    private javax.swing.JLabel lbl_dashv_ln1;
    private javax.swing.JLabel lbl_dashv_marital;
    private javax.swing.JLabel lbl_dashv_marital1;
    private javax.swing.JLabel lbl_dashv_mobile;
    private javax.swing.JLabel lbl_dashv_mobile1;
    private javax.swing.JLabel lbl_dashv_nid;
    private javax.swing.JLabel lbl_dashv_nid1;
    private javax.swing.JLabel lbl_dashv_occu;
    private javax.swing.JLabel lbl_dashv_occu1;
    private javax.swing.JLabel lbl_dashv_zip;
    private javax.swing.JLabel lbl_dashv_zip1;
    private javax.swing.JLabel lbl_feedb;
    private javax.swing.JLabel lbl_feedb_bg;
    private javax.swing.JLabel lbl_nid;
    private javax.swing.JLabel lbl_nid1;
    private javax.swing.JLabel line_chat;
    private javax.swing.JLabel line_feedb;
    private javax.swing.JPanel mailPanel;
    private javax.swing.JButton max;
    private javax.swing.JButton menu;
    private keeptoo.KGradientPanel menu_panel;
    private javax.swing.JButton min;
    private javax.swing.JPanel pan_dash_profile_bg;
    private javax.swing.JPanel pan_layer_nid;
    private javax.swing.JPanel pan_layer_nid1;
    private javax.swing.JPanel pnl_addm;
    private javax.swing.JPanel pnl_chat;
    private javax.swing.JPanel pnl_dash;
    private javax.swing.JPanel pnl_dash_dashboard;
    private ca.bank.KGradientPanel pnl_dash_editInfoButton;
    private ca.bank.KGradientPanel pnl_dash_returnbutton;
    private ca.bank.KGradientPanel pnl_dash_returnbutton1;
    private ca.bank.KGradientPanel pnl_dash_saveInfoButton;
    private ca.bank.KGradientPanel pnl_dash_showInfoButton;
    private javax.swing.JPanel pnl_dash_userinfo;
    private javax.swing.JPanel pnl_dash_userinfo_edit;
    private javax.swing.JPanel pnl_feedb;
    private javax.swing.JPanel pnl_feedb1;
    private javax.swing.JPanel pnl_tran;
    private javax.swing.JPanel pnl_transfr;
    private javax.swing.JLabel profile;
    private javax.swing.JScrollPane read_mail_scroll;
    private javax.swing.JSeparator separ;
    private javax.swing.JButton sign_out;
    private javax.swing.JTextArea ta_mail;
    private javax.swing.JTable table_tran;
    private javax.swing.JTextField tf_edit_addr;
    private javax.swing.JTextField tf_edit_fn;
    private javax.swing.JTextField tf_edit_ln;
    private javax.swing.JTextField tf_edit_nid;
    private javax.swing.JTextField tf_edit_num;
    private javax.swing.JTextField tf_edit_zip;
    // End of variables declaration//GEN-END:variables
}
