/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.bank;

/**
 *
 * @author Chondromollika_Ahmed
 * 
 */

import ca.bank.fadeFrame;

import Animacion.Animacion;
import AppPackage.AnimationClass;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;

public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    
    
    AnimationClass obj;
    Image img = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Lenovo\\Desktop\\CA BANK\\src\\ca\\bank\\resources\\icons\\icons8_flower_127px.png");  

// And set it
    public Welcome() {
        this.setIconImage(img);
        
        this.setUndecorated(rootPaneCheckingEnabled);
        this.setTitle("CA BANK");
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        manager.setVisible(false);
       client.setVisible(false);
       frontOfficer.setVisible(false);
        
        
        obj=new AnimationClass();
        obj.jLabelXRight(-400, 20, 10, 10, welText);
     //   Animacion.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        first = new keeptoo.KGradientPanel();
        name = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        welText = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        second = new keeptoo.KGradientPanel();
        client = new keeptoo.KButton();
        manager = new keeptoo.KButton();
        frontOfficer = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        first.setkEndColor(new java.awt.Color(0, 255, 255));
        first.setkStartColor(new java.awt.Color(255, 102, 255));
        first.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/logos/CA_BANK.png"))); // NOI18N
        first.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 710, 190));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_bank_127px.png"))); // NOI18N
        first.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 130, 130));

        welText.setFont(new java.awt.Font("Magneto", 0, 48)); // NOI18N
        welText.setForeground(new java.awt.Color(255, 255, 255));
        welText.setText("Welcome To The");
        first.add(welText, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 170, 460, 110));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_fast_forward_80px.png"))); // NOI18N
        next.setBorder(null);
        next.setContentAreaFilled(false);
        next.setFocusPainted(false);
        next.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_fast_forward_60px.png"))); // NOI18N
        next.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_next_page_60px.png"))); // NOI18N
        next.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/bank/resources/icons/icons8_fast_forward_80px.png"))); // NOI18N
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextMousePressed(evt);
            }
        });
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        first.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, -1, -1));

        getContentPane().add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 640));

        second.setkEndColor(new java.awt.Color(0, 255, 0));
        second.setkGradientFocus(900);
        second.setkStartColor(new java.awt.Color(255, 51, 102));
        second.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        client.setBorder(null);
        client.setText("client");
        client.setBorderPainted(false);
        client.setFocusable(false);
        client.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        client.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        client.setkBorderRadius(80);
        client.setkEndColor(new java.awt.Color(255, 204, 255));
        client.setkFillButton(false);
        client.setkHoverForeGround(new java.awt.Color(0, 255, 255));
        client.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        client.setkIndicatorThickness(0);
        client.setkPressedColor(new java.awt.Color(255, 102, 102));
        client.setkSelectedColor(new java.awt.Color(0, 255, 0));
        client.setkStartColor(new java.awt.Color(0, 255, 255));
        client.setMargin(new java.awt.Insets(0, 0, 0, 0));
        client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientActionPerformed(evt);
            }
        });
        second.add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 240, 80));

        manager.setText("Manager");
        manager.setBorderPainted(false);
        manager.setContentAreaFilled(false);
        manager.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        manager.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        manager.setkBorderRadius(80);
        manager.setkEndColor(new java.awt.Color(255, 204, 255));
        manager.setkFillButton(false);
        manager.setkHoverForeGround(new java.awt.Color(0, 255, 255));
        manager.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        manager.setkIndicatorThickness(0);
        manager.setkPressedColor(new java.awt.Color(255, 102, 102));
        manager.setkSelectedColor(new java.awt.Color(0, 255, 0));
        manager.setkStartColor(new java.awt.Color(0, 255, 255));
        manager.setMargin(new java.awt.Insets(0, 0, 0, 0));
        manager.setRequestFocusEnabled(false);
        manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerActionPerformed(evt);
            }
        });
        second.add(manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 240, 80));

        frontOfficer.setBorder(null);
        frontOfficer.setText("Front officer");
        frontOfficer.setBorderPainted(false);
        frontOfficer.setContentAreaFilled(false);
        frontOfficer.setFocusPainted(false);
        frontOfficer.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        frontOfficer.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        frontOfficer.setkBorderRadius(80);
        frontOfficer.setkEndColor(new java.awt.Color(255, 204, 255));
        frontOfficer.setkFillButton(false);
        frontOfficer.setkHoverForeGround(new java.awt.Color(0, 255, 255));
        frontOfficer.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        frontOfficer.setkIndicatorThickness(0);
        frontOfficer.setkPressedColor(new java.awt.Color(255, 102, 102));
        frontOfficer.setkSelectedColor(new java.awt.Color(0, 255, 0));
        frontOfficer.setkStartColor(new java.awt.Color(0, 255, 255));
        frontOfficer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        frontOfficer.setRequestFocusEnabled(false);
        frontOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontOfficerActionPerformed(evt);
            }
        });
        second.add(frontOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 240, 80));

        getContentPane().add(second, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMousePressed



        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_nextMousePressed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
 
       Animacion.mover_izquierda(0, -1080, 10, 10,first);
       
       
        Timer t=new Timer();
        t.schedule(new TimerTask() {
           @Override
           public void run() {
               
               manager.setVisible(true);
       client.setVisible(true);
       frontOfficer.setVisible(true);
       first.setVisible(false);
               //To change body of generated methods, choose Tools | Templates.
           }
       }, 1800);
       
       
        
       
       
       
       
       
    }//GEN-LAST:event_nextActionPerformed

    private void clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientActionPerformed
        fadeFrame.JFrameFadeOut(1.0f,0.0f , 0.005f, 10, this, 2);
       
        new ClientLogin().setVisible(true);
    }//GEN-LAST:event_clientActionPerformed

    private void managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerActionPerformed
        // TODO add your handling code here:
        
        fadeFrame.JFrameFadeOut(1.0f,0.0f , 0.005f, 10, this, 2);
        new AdminLogin();

    }//GEN-LAST:event_managerActionPerformed

    private void frontOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontOfficerActionPerformed

        fadeFrame.JFrameFadeOut(1.0f,0.0f , 0.005f, 10, this, 2);
        new OfficerLogin().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_frontOfficerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    //-- .- -.-- -... . / .-.. .. -- .. - / .. ... / - --- --- / -. . .- .-. .-.-.- .-.-.- .-.-.- / .. -.. -.-
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton client;
    private keeptoo.KGradientPanel first;
    private keeptoo.KButton frontOfficer;
    private javax.swing.JLabel icon;
    private keeptoo.KButton manager;
    private javax.swing.JLabel name;
    private javax.swing.JButton next;
    private keeptoo.KGradientPanel second;
    private javax.swing.JLabel welText;
    // End of variables declaration//GEN-END:variables
}
